// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type xdpflowFlowKey struct {
	_     structs.HostLayout
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
	Proto uint8
	Pad   [3]uint8
}

type xdpflowFlowStats struct {
	_               structs.HostLayout
	Packets         uint64
	Bytes           uint64
	DpiCaptureCount uint8
	Pad             [5]uint8
	SvcPort         uint16
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	xdpflowMapDpiEvents     = "dpi_events"
	xdpflowMapFlowStatsMap  = "flow_stats_map"
	xdpflowMapHttpEvents    = "http_events"
	xdpflowMapSniEvents     = "sni_events"
	xdpflowProgXdpFlowCount = "xdp_flow_count"
)

// loadXdpflow returns the embedded CollectionSpec for xdpflow.
func loadXdpflow() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpflowBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdpflow: %w", err)
	}

	return spec, err
}

// loadXdpflowObjects loads xdpflow and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpflowObjects
//	*xdpflowPrograms
//	*xdpflowMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpflowObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdpflow()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpflowSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpflowSpecs struct {
	xdpflowProgramSpecs
	xdpflowMapSpecs
	xdpflowVariableSpecs
}

// xdpflowProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpflowProgramSpecs struct {
	XdpFlowCount *ebpf.ProgramSpec `ebpf:"xdp_flow_count"`
}

// xdpflowMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpflowMapSpecs struct {
	DpiEvents    *ebpf.MapSpec `ebpf:"dpi_events"`
	FlowStatsMap *ebpf.MapSpec `ebpf:"flow_stats_map"`
	HttpEvents   *ebpf.MapSpec `ebpf:"http_events"`
	SniEvents    *ebpf.MapSpec `ebpf:"sni_events"`
}

// xdpflowVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpflowVariableSpecs struct {
}

// xdpflowObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpflowObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpflowObjects struct {
	xdpflowPrograms
	xdpflowMaps
	xdpflowVariables
}

func (o *xdpflowObjects) Close() error {
	return _XdpflowClose(
		&o.xdpflowPrograms,
		&o.xdpflowMaps,
	)
}

// xdpflowMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpflowObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpflowMaps struct {
	DpiEvents    *ebpf.Map `ebpf:"dpi_events"`
	FlowStatsMap *ebpf.Map `ebpf:"flow_stats_map"`
	HttpEvents   *ebpf.Map `ebpf:"http_events"`
	SniEvents    *ebpf.Map `ebpf:"sni_events"`
}

func (m *xdpflowMaps) Close() error {
	return _XdpflowClose(
		m.DpiEvents,
		m.FlowStatsMap,
		m.HttpEvents,
		m.SniEvents,
	)
}

// xdpflowVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdpflowObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpflowVariables struct {
}

// xdpflowPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpflowObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpflowPrograms struct {
	XdpFlowCount *ebpf.Program `ebpf:"xdp_flow_count"`
}

func (p *xdpflowPrograms) Close() error {
	return _XdpflowClose(
		p.XdpFlowCount,
	)
}

func _XdpflowClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpflow_bpfel.o
var _XdpflowBytes []byte
